# Generated by Django 3.2.4 on 2023-09-12 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='myproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('product_pic', models.ImageField(null=True, upload_to='', verbose_name='static/product/')),
                ('total_discount', models.IntegerField()),
                ('product_quantity', models.CharField(max_length=200)),
                ('pdate', models.DateField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('subcategory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subcategory')),
            ],
        ),
    ]
